name: gp_12dim
type: test
bounds: [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]
lengthscales: [0.75, 1, 2, 2, 4, 4, 4, 4, 8, 8, 8, 8]
negate: False
noise_std: 0.25
